# https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=python

# application: bridgy-federated

runtime: python312

# default_expiration: 1h

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 30 --timeout 60 -b :$PORT app:app

# background: https://github.com/snarfed/bridgy/issues/578
# https://github.com/snarfed/bridgy/issues/1051
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .9
  min_pending_latency: 500ms
  max_concurrent_requests: 30

inbound_services:
- warmup

# Serverless VPC Access for Memorystore memcache
# https://cloud.google.com/vpc/docs/serverless-vpc-access
vpc_access_connector:
  name: projects/bridgy-federated/locations/us-central1/connectors/bridgy-fed

env_variables:
  PDS_HOST: fed.brid.gy
  PLC_HOST: plc.directory
  APPVIEW_HOST: api.bsky.app
  BGS_HOST: bsky.network
  MOD_SERVICE_HOST: mod.bsky.app
  MOD_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
  MEMCACHE_HOST: '10.126.144.3'
  # ...or test against labeler.dholms.xyz / did:plc:vzxheqfwpbi3lxbgdh22js66

  # https://github.com/googleapis/python-ndb/blob/c55ec62b5153787404488b046c4bf6ffa02fee64/google/cloud/ndb/utils.py#L78-L81
  NDB_DEBUG: true

handlers:

# static
- url: /static
  static_dir: static
  secure: always

- url: /oauth_dropins_static
  static_dir: oauth_dropins_static

- url: /fonts
  static_dir: oauth_dropins_fonts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /.well-known/security.txt
  static_files: static/security.txt
  upload: static/security.txt
  secure: always

# dynamic
- url: .*
  script: auto
  secure: always
